nelmio_api_doc:
    documentation:
        info:
            title: StartupBackend API
            description: Documentation de l'API StartupBackend
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)